/* ═══════════════════════════════════════════
   VELOCE — Vehicle Data Layer
   Shared across home, inventory and detail pages
   ═══════════════════════════════════════════ */

const IMG = (id, w = 1600) =>
  `https://images.unsplash.com/${id}?q=80&w=${w}&auto=format&fit=crop`;

// Generic gallery shots (interior / detail / road)
const SHOT = {
  interior: "photo-1489824904134-891ab64532f1",
  detailRed: "photo-1542282088-fe8426682b8f",
  road: "photo-1449965408869-eaa3f722e40d",
  night: "photo-1605559424843-9e4c228bf1c2",
  coast: "photo-1502877338535-766e1452684a",
  silver: "photo-1542362567-b07e54358753",
};

const CARS = [
  {
    id: "ferrari-488-gtb",
    paint: "#d1001f",
    sketchfab: "929feda77330442c892c334522d6ec10",
    brand: "Ferrari",
    model: "488 GTB",
    tagline: "Turbocharged perfection from Maranello.",
    price: 285000,
    year: 2021,
    mileage: "8,400 km",
    hp: 670,
    topSpeed: 330,
    accel: 3.0,
    torque: 760,
    engine: "3.9L Twin-Turbo V8",
    transmission: "7-Speed DCT",
    drivetrain: "RWD",
    exterior: "Rosso Corsa",
    interior: "Nero Leather",
    badge: "Just Arrived",
    featured: true,
    description:
      "The 488 GTB marked Ferrari's triumphant return to turbocharging — and it did so without losing a drop of soul. Its 3.9-litre twin-turbo V8 was named International Engine of the Year four times in a row, delivering savage acceleration with zero perceptible lag. This example comes with a full Ferrari service history and factory carbon-fibre options.",
    features: [
      "Carbon-fibre racing seats",
      "Front-lift suspension system",
      "Full Ferrari service history",
      "Carbon interior package",
      "Apple CarPlay integration",
      "Scuderia Ferrari shields",
    ],
    ratings: { performance: 96, handling: 93, comfort: 74, exclusivity: 92 },
    image: "photo-1583121274602-3e2820c69888",
    gallery: [SHOT.detailRed, SHOT.interior],
  },
  {
    id: "lamborghini-huracan-evo",
    paint: "#f2b705",
    sketchfab: "ac4bfe9c5e8d42fda5691f78e8931b95",
    brand: "Lamborghini",
    model: "Huracán EVO",
    tagline: "A naturally aspirated V10 war cry.",
    price: 320000,
    year: 2022,
    mileage: "5,200 km",
    hp: 640,
    topSpeed: 325,
    accel: 2.9,
    torque: 600,
    engine: "5.2L V10",
    transmission: "7-Speed DCT",
    drivetrain: "AWD",
    exterior: "Giallo Inti",
    interior: "Alcantara Nero",
    badge: "Rare Spec",
    featured: true,
    description:
      "One of the last of its kind — a naturally aspirated V10 screaming to 8,500 rpm. The Huracán EVO adds rear-wheel steering and Lamborghini's LDVI predictive dynamics brain to an already legendary chassis. Finished in striking Giallo Inti with a full Alcantara cabin, this is an analogue icon in a digital world.",
    features: [
      "Rear-wheel steering",
      "LDVI predictive dynamics",
      "Lifting system",
      "Style package in gloss black",
      "Sensonum premium audio",
      "Transparent engine bonnet",
    ],
    ratings: { performance: 97, handling: 95, comfort: 70, exclusivity: 94 },
    image: "photo-1618843479313-40f8afb4b4d8",
    gallery: [SHOT.coast, SHOT.interior],
  },
  {
    id: "porsche-911-carrera-s",
    paint: "#f5c800",
    sketchfab: "d01b254483794de3819786d93e0e1ebf",
    brand: "Porsche",
    model: "911 Carrera S",
    tagline: "The benchmark. Sixty years in the making.",
    price: 148000,
    year: 2023,
    mileage: "12,000 km",
    hp: 450,
    topSpeed: 308,
    accel: 3.5,
    torque: 530,
    engine: "3.0L Twin-Turbo Flat-6",
    transmission: "8-Speed PDK",
    drivetrain: "RWD",
    exterior: "Racing Yellow",
    interior: "Black Leather",
    badge: "Popular",
    featured: true,
    description:
      "There is a reason every sports car is measured against the 911. The 992-generation Carrera S blends everyday usability with genuine supercar pace, its twin-turbo flat-six and lightning-fast PDK gearbox delivering relentless, repeatable performance. This example is specified in iconic Racing Yellow with the Sport Chrono package.",
    features: [
      "Sport Chrono package",
      "PASM sport suspension",
      "Sports exhaust system",
      "BOSE surround sound",
      "18-way adaptive sport seats",
      "Porsche approved warranty",
    ],
    ratings: { performance: 90, handling: 96, comfort: 86, exclusivity: 78 },
    image: "photo-1503376780353-7e6692767b70",
    gallery: [SHOT.night, SHOT.interior],
  },
  {
    id: "bmw-m4-competition",
    paint: "#0f5c46",
    sketchfab: "d3f07b471d9f4a2c9a2acf79d88a3645",
    brand: "BMW",
    model: "M4 Competition",
    tagline: "Precision engineering with a violent streak.",
    price: 97500,
    year: 2023,
    mileage: "9,800 km",
    hp: 510,
    topSpeed: 290,
    accel: 3.9,
    torque: 650,
    engine: "3.0L Twin-Turbo Inline-6",
    transmission: "8-Speed M Steptronic",
    drivetrain: "RWD",
    exterior: "Isle of Man Green",
    interior: "Kyalami Orange Merino",
    badge: null,
    featured: false,
    description:
      "The M4 Competition is the daily-drivable weapon of the range. Its S58 twin-turbo straight-six is one of the great modern engines — 510 hp of relentless mid-range punch — wrapped in a chassis that rewards commitment. Specified with carbon bucket seats and the striking Kyalami Orange interior.",
    features: [
      "M Carbon bucket seats",
      "M Drive Professional",
      "Carbon exterior package",
      "Harman Kardon audio",
      "Laser headlights",
      "M Driver's package",
    ],
    ratings: { performance: 88, handling: 89, comfort: 84, exclusivity: 68 },
    image: "photo-1617531653332-bd46c24f2068",
    gallery: ["photo-1555215695-3004980ad54e", SHOT.interior],
  },
  {
    id: "porsche-taycan-turbo-s",
    paint: "#a9c7d8",
    sketchfab: "4e1abafe7cf5413587a421377624ba08",
    brand: "Porsche",
    model: "Taycan Turbo S",
    tagline: "The future, delivered at 2.8 seconds.",
    price: 169000,
    year: 2023,
    mileage: "6,100 km",
    hp: 761,
    topSpeed: 260,
    accel: 2.8,
    torque: 1050,
    engine: "Dual-Motor Electric",
    transmission: "2-Speed (rear axle)",
    drivetrain: "AWD",
    exterior: "Frozen Blue Metallic",
    interior: "Black / Chalk",
    badge: "Electric",
    featured: true,
    description:
      "Porsche's first electric car didn't just meet expectations — it redefined what an EV could feel like. With 761 hp on overboost and a two-speed rear transmission, the Taycan Turbo S launches with violence yet corners like a proper Porsche. 800-volt architecture means charging is as rapid as the car itself.",
    features: [
      "Performance Battery Plus",
      "Porsche Dynamic Chassis Control",
      "Rear-axle steering",
      "Panoramic fixed glass roof",
      "BOSE surround sound",
      "22kW onboard AC charger",
    ],
    ratings: { performance: 95, handling: 88, comfort: 92, exclusivity: 82 },
    image: "photo-1614200187524-dc4b892acf16",
    gallery: [SHOT.silver, SHOT.interior],
  },
  {
    id: "nissan-gtr-nismo",
    paint: "#5a5d61",
    sketchfab: "20a14338df064c06a3606bab6894adbc",
    brand: "Nissan",
    model: "GT-R Nismo",
    tagline: "Godzilla. Hand-built and track-honed.",
    price: 123000,
    year: 2021,
    mileage: "14,500 km",
    hp: 600,
    topSpeed: 315,
    accel: 2.7,
    torque: 652,
    engine: "3.8L Twin-Turbo V6",
    transmission: "6-Speed DCT",
    drivetrain: "AWD",
    exterior: "Stealth Gray",
    interior: "Black / Red Recaro",
    badge: null,
    featured: false,
    description:
      "Each GT-R Nismo engine is hand-assembled by a single takumi master craftsman, its turbochargers lifted straight from GT3 racing. Combined with Nissan's legendary ATTESA all-wheel-drive system, the result is one of the most devastating point-to-point cars ever built — a cult legend in its final, sharpest form.",
    features: [
      "Hand-built takumi engine",
      "GT3-spec turbochargers",
      "Carbon-ceramic brakes",
      "Recaro carbon bucket seats",
      "Carbon roof and bonnet",
      "Nismo aerodynamic package",
    ],
    ratings: { performance: 93, handling: 91, comfort: 66, exclusivity: 85 },
    image: "photo-1525609004556-c46c7d6cf023",
    gallery: ["photo-1568605117036-5fe5e7bab0b7", SHOT.interior],
  },
  {
    id: "chevrolet-corvette-c8",
    paint: "#1163c9",
    sketchfab: "790c40ccff6843eab0b7b4bd18421ff8",
    brand: "Chevrolet",
    model: "Corvette C8 Stingray",
    tagline: "America's mid-engined revolution.",
    price: 86000,
    year: 2022,
    mileage: "11,200 km",
    hp: 495,
    topSpeed: 312,
    accel: 2.9,
    torque: 637,
    engine: "6.2L V8",
    transmission: "8-Speed DCT",
    drivetrain: "RWD",
    exterior: "Rapid Blue",
    interior: "Jet Black",
    badge: "Showcase",
    featured: false,
    description:
      "For the first time in nearly seventy years, the Corvette moved its engine behind the driver — and instantly rewrote the supercar value equation. The C8 Stingray's naturally aspirated 6.2-litre V8 delivers exotic-car pace and theatre at a fraction of the usual cost of entry. Z51 performance package included.",
    features: [
      "Z51 performance package",
      "Magnetic Ride Control 4.0",
      "Performance exhaust",
      "Front-lift with GPS memory",
      "Bose 14-speaker audio",
      "Removable roof panel",
    ],
    ratings: { performance: 89, handling: 87, comfort: 82, exclusivity: 72 },
    image: "photo-1552519507-da3b142c6e3d",
    gallery: [SHOT.road, SHOT.interior],
  },
  {
    id: "mercedes-amg-gt-r",
    paint: "#3a3f44",
    sketchfab: "fbff228fb1a94d34b808c57264ab7103",
    brand: "Mercedes-AMG",
    model: "GT R",
    tagline: "The Beast of the Green Hell.",
    price: 189000,
    year: 2021,
    mileage: "7,900 km",
    hp: 585,
    topSpeed: 318,
    accel: 3.6,
    torque: 700,
    engine: "4.0L Twin-Turbo V8",
    transmission: "7-Speed DCT",
    drivetrain: "RWD",
    exterior: "Designo Graphite",
    interior: "Black Nappa / Dinamica",
    badge: "Showcase",
    featured: false,
    description:
      "Developed on the Nürburgring Nordschleife — the 'Green Hell' that gave it its nickname — the AMG GT R is the most focused expression of the GT line. Active aero, rear-wheel steering and a nine-stage traction control dial borrowed from the GT3 race car make it a precision instrument with a thunderous V8 heart.",
    features: [
      "AMG Track Package",
      "Rear-wheel steering",
      "9-stage traction control",
      "Carbon-ceramic brakes",
      "AMG carbon bucket seats",
      "Burmester surround sound",
    ],
    ratings: { performance: 94, handling: 94, comfort: 72, exclusivity: 88 },
    image: "photo-1544636331-e26879cd4d9b",
    gallery: [SHOT.night, SHOT.interior],
  },
  {
    id: "bmw-m8-gran-coupe",
    paint: "#4e6a76",
    sketchfab: "f69bc7c528804552b2ff032d7c1e9fb4",
    brand: "BMW",
    model: "M8 Gran Coupé",
    tagline: "Grand touring at the speed of light.",
    price: 146000,
    year: 2022,
    mileage: "13,400 km",
    hp: 625,
    topSpeed: 305,
    accel: 3.2,
    torque: 750,
    engine: "4.4L Twin-Turbo V8",
    transmission: "8-Speed M Steptronic",
    drivetrain: "AWD",
    exterior: "Frozen Bluestone",
    interior: "Silverstone Merino",
    badge: "Showcase",
    featured: false,
    description:
      "The M8 Gran Coupé is BMW's flagship answer to the question: why choose between a limousine and a supercar? Its 625 hp V8 and switchable M xDrive system deliver crushing cross-continent pace, while the four-door cabin cossets in full Merino leather. Effortless, elegant, and extraordinarily fast.",
    features: [
      "M xDrive with 2WD mode",
      "M Carbon exterior package",
      "Bowers & Wilkins Diamond audio",
      "M Multifunction seats",
      "Soft-close doors",
      "Driving Assistant Professional",
    ],
    ratings: { performance: 90, handling: 84, comfort: 93, exclusivity: 80 },
    image: "photo-1580273916550-e323be2ae537",
    gallery: ["photo-1523983388277-336a66bf9bcd", SHOT.interior],
  },
  {
    id: "porsche-718-cayman-gts",
    paint: "#b9bcbe",
    sketchfab: "357999b7e87642e38062623127a61bb2",
    brand: "Porsche",
    model: "718 Cayman GTS 4.0",
    tagline: "Pure driving, distilled.",
    price: 102000,
    year: 2023,
    mileage: "4,700 km",
    hp: 400,
    topSpeed: 293,
    accel: 4.0,
    torque: 430,
    engine: "4.0L Flat-6",
    transmission: "6-Speed Manual",
    drivetrain: "RWD",
    exterior: "GT Silver Metallic",
    interior: "Black Race-Tex",
    badge: "Showcase",
    featured: false,
    description:
      "A naturally aspirated 4.0-litre flat-six, a six-speed manual gearbox, and a mid-engined chassis regarded as one of the finest ever made. The Cayman GTS 4.0 is the enthusiast's choice — a car bought not for numbers but for the way it makes every single drive feel like an occasion.",
    features: [
      "6-speed manual gearbox",
      "PASM sport suspension (-20mm)",
      "Sport Chrono package",
      "Sports exhaust system",
      "GTS interior package",
      "Torque vectoring with LSD",
    ],
    ratings: { performance: 84, handling: 97, comfort: 80, exclusivity: 79 },
    image: "photo-1553440569-bcc63803a83d",
    gallery: [SHOT.coast, SHOT.interior],
  },
  {
    id: "lamborghini-aventador-s",
    paint: "#17181a",
    sketchfab: "69ed4dbc7b5b416a88280b49d5fe9869",
    brand: "Lamborghini",
    model: "Aventador S",
    tagline: "The last of the great V12 flagships.",
    price: 465000,
    year: 2020,
    mileage: "6,800 km",
    hp: 740,
    topSpeed: 350,
    accel: 2.9,
    torque: 690,
    engine: "6.5L V12",
    transmission: "7-Speed ISR",
    drivetrain: "AWD",
    exterior: "Nero Aldebaran",
    interior: "Nero Ade / Rosso",
    badge: "V12 Icon",
    featured: true,
    description:
      "A naturally aspirated 6.5-litre V12 screaming to 8,500 rpm, scissor doors, and a soundtrack no turbocharged car will ever replicate. The Aventador S added four-wheel steering and a sharpened aero package to the raging bull's flagship — a future classic in the making, finished in menacing Nero Aldebaran.",
    features: [
      "Four-wheel steering",
      "EGO custom drive mode",
      "Carbon-fibre monocoque",
      "Lifting system",
      "Scissor doors",
      "Sensonum premium audio",
    ],
    ratings: { performance: 98, handling: 90, comfort: 62, exclusivity: 97 },
    image: "photo-1571607388263-1044f9ea01dd",
    gallery: ["photo-1621135802920-133df287f89c", SHOT.interior],
  },
  {
    id: "mclaren-720s",
    paint: "#c8cdd2",
    sketchfab: "e820cf40821940bcafebf24bec693d16",
    brand: "McLaren",
    model: "720S",
    tagline: "Physics, politely ignored.",
    price: 315000,
    year: 2021,
    mileage: "7,400 km",
    hp: 720,
    topSpeed: 341,
    accel: 2.9,
    torque: 770,
    engine: "4.0L Twin-Turbo V8",
    transmission: "7-Speed SSG",
    drivetrain: "RWD",
    exterior: "Supernova Silver",
    interior: "Carbon Black Alcantara",
    badge: "Just Arrived",
    featured: true,
    description:
      "The 720S didn't move the supercar goalposts — it stole them. A carbon Monocage II chassis, hydraulically cross-linked suspension and 720 horsepower make it devastating on track yet strangely gentle on the road. Many call it the most complete supercar of its generation. We don't argue.",
    features: [
      "Proactive Chassis Control II",
      "Carbon Monocage II",
      "Variable Drift Control",
      "Dihedral doors",
      "Track Telemetry with cameras",
      "Bowers & Wilkins audio",
    ],
    ratings: { performance: 97, handling: 96, comfort: 71, exclusivity: 93 },
    image: "photo-1542362567-b07e54358753",
    gallery: [SHOT.night, SHOT.interior],
  },
  {
    id: "audi-r8-v10",
    paint: "#101214",
    sketchfab: "0701d14ce550407f900df891316788f0",
    brand: "Audi",
    model: "R8 V10 Performance",
    tagline: "The everyday supercar, perfected.",
    price: 210000,
    year: 2022,
    mileage: "9,100 km",
    hp: 620,
    topSpeed: 331,
    accel: 3.1,
    torque: 580,
    engine: "5.2L V10",
    transmission: "7-Speed S tronic",
    drivetrain: "AWD",
    exterior: "Mythos Black",
    interior: "Black Fine Nappa",
    badge: null,
    featured: false,
    description:
      "Sharing its howling V10 heart with the Huracán, the R8 wraps supercar theatre in a body you could genuinely drive every single day. Quattro all-wheel drive, a cabin built with Audi's obsessive precision, and one of the last naturally aspirated engines on sale — this is the thinking person's exotic.",
    features: [
      "Quattro all-wheel drive",
      "Audi Virtual Cockpit",
      "Magnetic ride suspension",
      "Carbon sideblades",
      "Bang & Olufsen audio",
      "Laser light package",
    ],
    ratings: { performance: 93, handling: 90, comfort: 84, exclusivity: 86 },
    image: "photo-1493238792000-8113da705763",
    gallery: [SHOT.road, SHOT.interior],
  },
  {
    id: "lamborghini-huracan-performante",
    paint: "#ece9e2",
    sketchfab: "ea7b91e22b8848ac8d02c79b1c574fc1",
    brand: "Lamborghini",
    model: "Huracán Performante",
    tagline: "The Nürburgring record breaker.",
    price: 340000,
    year: 2019,
    mileage: "11,600 km",
    hp: 640,
    topSpeed: 325,
    accel: 2.9,
    torque: 600,
    engine: "5.2L V10",
    transmission: "7-Speed DCT",
    drivetrain: "AWD",
    exterior: "Bianco Monocerus",
    interior: "Nero Alcantara / Bianco",
    badge: "Collector Grade",
    featured: false,
    description:
      "When it launched, the Performante lapped the Nürburgring faster than million-euro hypercars — thanks to ALA, Lamborghini's ingenious active aero that vectors downforce side to side through the wing. Forged composite everywhere, a V10 at full war cry, and white-on-black spec that collectors chase.",
    features: [
      "ALA active aerodynamics",
      "Forged composite aero parts",
      "Titanium exhaust valves",
      "Carbon bucket seats",
      "Bronze forged wheels",
      "Nürburgring record heritage",
    ],
    ratings: { performance: 96, handling: 97, comfort: 65, exclusivity: 95 },
    image: "photo-1544829099-b9a0c07fad1a",
    gallery: ["photo-1511919884226-fd3cad34687c", SHOT.interior],
  },
  {
    id: "ferrari-488-spider",
    paint: "#d1001f",
    sketchfab: "e542a8f3cf274ba9805ec2b09bee6567",
    brand: "Ferrari",
    model: "488 Spider",
    tagline: "The V8 symphony, open air edition.",
    price: 310000,
    year: 2020,
    mileage: "9,900 km",
    hp: 670,
    topSpeed: 325,
    accel: 3.0,
    torque: 760,
    engine: "3.9L Twin-Turbo V8",
    transmission: "7-Speed DCT",
    drivetrain: "RWD",
    exterior: "Rosso Corsa",
    interior: "Cuoio Leather",
    badge: "Open Top",
    featured: false,
    description:
      "Everything that makes the 488 GTB brilliant, plus the sky. The retractable hardtop folds away in fourteen seconds, turning every tunnel into a concert hall for that twin-turbo V8. Structural rigidity is barely compromised, which means neither is the driving experience. Rosso over Cuoio — the classic recipe.",
    features: [
      "Retractable hardtop (14s)",
      "Front-lift suspension",
      "Carbon driving zone",
      "Cuoio heritage interior",
      "Apple CarPlay integration",
      "Full Ferrari service history",
    ],
    ratings: { performance: 95, handling: 91, comfort: 76, exclusivity: 93 },
    image: "photo-1606220838315-056192d5e927",
    gallery: ["photo-1583121274602-3e2820c69888", SHOT.interior],
  },
  {
    id: "ford-mustang-gt",
    paint: "#4a4e53",
    sketchfab: "3d005089037f4b3cbbfed3d6ba188466",
    brand: "Ford",
    model: "Mustang GT",
    tagline: "An American icon with a 5.0 heart.",
    price: 62000,
    year: 2022,
    mileage: "15,300 km",
    hp: 450,
    topSpeed: 250,
    accel: 4.3,
    torque: 529,
    engine: "5.0L V8",
    transmission: "10-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Magnetic Gray",
    interior: "Ebony Leather",
    badge: null,
    featured: false,
    description:
      "Sixty years of muscle car heritage distilled into one unmistakable silhouette. The Coyote 5.0 V8 delivers its 450 horses with an old-school rumble that no downsized turbo engine can match, while the 10-speed automatic makes it an effortless daily. The most attainable V8 icon in our collection.",
    features: [
      "Coyote 5.0 V8",
      "Active performance exhaust",
      "MagneRide suspension",
      "Recaro sport seats",
      "Track Apps telemetry",
      "Line-lock launch control",
    ],
    ratings: { performance: 80, handling: 76, comfort: 79, exclusivity: 55 },
    image: "photo-1494976388531-d1058494cdd8",
    gallery: [SHOT.road, SHOT.interior],
  },
  {
    id: "bmw-m440i",
    paint: "#1867c0",
    sketchfab: "a41efb9c01e64d9d81a7896d2bbbb167",
    brand: "BMW",
    model: "M440i xDrive",
    tagline: "The sweet spot of the 4 Series.",
    price: 58000,
    year: 2021,
    mileage: "21,000 km",
    hp: 374,
    topSpeed: 250,
    accel: 4.5,
    torque: 500,
    engine: "3.0L Turbo Inline-6",
    transmission: "8-Speed Steptronic",
    drivetrain: "AWD",
    exterior: "Portimao Blue",
    interior: "Black Vernasca",
    badge: null,
    featured: false,
    description:
      "The M440i is the connoisseur's pick of the 4 Series range — the silky B58 straight-six with a mild-hybrid boost, xDrive security, and genuine M-car pace without the M-car price. Finished in Portimao Blue, it's the perfect gateway into performance BMW ownership.",
    features: [
      "B58 straight-six engine",
      "48V mild-hybrid system",
      "xDrive all-wheel drive",
      "M Sport differential",
      "Adaptive M suspension",
      "Harman Kardon audio",
    ],
    ratings: { performance: 78, handling: 80, comfort: 88, exclusivity: 48 },
    image: "photo-1502877338535-766e1452684a",
    gallery: [SHOT.night, SHOT.interior],
  },
];

const SHOWCASE_IDS = [
  "chevrolet-corvette-c8",
  "mercedes-amg-gt-r",
  "bmw-m8-gran-coupe",
  "porsche-718-cayman-gts",
];

const fmtPrice = (n) => "$" + n.toLocaleString("en-US");
const getCar = (id) => CARS.find((c) => c.id === id);
const carUrl = (id) => `car.html?id=${id}`;
